## Source Order: #1
## Expect this to override existing $HOME/.bash_profile
echo "# PROFILE: .bash_profile" >&2
export PATH="$HOME/.local/bin:/opt/homebrew/bin:$PATH"

case $- in
    *i*) ;;
      *) return;;
esac

source_ifexists () {
  local file
  for file in $@; do 
    [[ -f "$file" ]] && source "$file"
  done
}

[[ -f ${HOME}/.bashrc" ]] && source ${HOME}/.bashrc

